<!DOCTYPE html>
<html lang="en">
<head>
<title>Welcome</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php include '../Controller/CSS.php';?>
</head>
<body>


<?php include '../Controller/headeral.php';?>

<section>
  
  <article>
    <h1>Welcome to AIUB Alumni Management System </h1>

  </article>
</section>



<?php include '../controller/FOOTER.php';?>


</body>
</html>